name: chexpert_envs
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter_contrib_nbextensions=0.5.1
  - pip=20.2.4
  - python=3.8.5
  - seaborn=0.11.1
  - pip:
    - libauc==1.1.8
    - matplotlib==3.3.3
    - numpy==1.22.3
    - pandas==1.4.2
    - pathlib2==2.3.0
    - pillow==8.0.1
    - scikit-learn==0.23.2
    - scipy==1.5.4
    - spacy==2.3.4
    - torch==1.9.0+cu111
    - transformers==4.1.1
    - fastcore==1.4.3
    - fastprogress==1.0.0
    - fastai==2.6.1
